default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] %>
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: dodonate_development


test:
  <<: *default
  database: dodonate_test