default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  database: <%= ENV.fetch("DB_NAME") { "dodonate" } %>
  username: <%= ENV.fetch("DB_USER") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "" }%>
  pool: 5

development:
  <<: *default
  database: dodonate_development


test:
  <<: *default
  database: dodonate_test
